import 'package:hive/hive.dart';

part 'events.g.dart'; // This will be generated by Hive generator

@HiveType(typeId: 0) // Choose a unique typeId (0-223)
class Event {
  @HiveField(0)
  final String id;
  @HiveField(1)
  final String title;
  @HiveField(2)
  final String userId;
  @HiveField(3)
  final DateTime startDate;
  @HiveField(4)
  final DateTime? endDate;
  @HiveField(5)
  final DateTime createdAt;
  @HiveField(6)
  final DateTime updatedAt;
  @HiveField(7)
  final String? description; // <-- Add this line
  @HiveField(8)
  final bool isSynced; // Non-nullable, default false
  @HiveField(9)
  final DateTime lastUpdated; // Non-nullable
  @HiveField(10)
  final int version; // Conflict resolution
  @HiveField(11)
  final bool isDeleted;
  @HiveField(12)
  String? changeType;

  Event({
    required this.id,
    this.isDeleted = false,
    required this.title,
    required this.userId,
    required this.startDate,
    this.endDate,
    required this.createdAt,
    required this.updatedAt,
    this.description,
    this.isSynced = false, // Default value
    required this.lastUpdated, // Required
    this.version = 0, // Default version
    this.changeType,
  });

  /// Convert Event object to JSON for sending to backend
  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'userId': userId,
      'start_date': startDate.toIso8601String(),
      'end_date': endDate?.toIso8601String(),
      'description': description,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'id': id,
      'isSynced': isSynced,
      'lastUpdated': lastUpdated.toIso8601String(),
      'version': version,
      'isDeleted': isDeleted,
      'changeType': changeType,
    };
  }

  factory Event.fromJson(Map<String, dynamic> json) {
    try {
      return Event(
        isDeleted: json['isDeleted'] ?? false,
        id: json['id'] ?? json['_id'] ?? '',
        // eventId: json['id'] ?? json['_id'] ?? '',
        title: json['title'] ?? '',
        userId: json['userId'] ?? json['user_id'] ?? json['createdBy'] ?? '',
        startDate: _parseDateTime(json['start_date'] ?? json['startDate']),
        endDate:
            json['end_date'] != null || json['endDate'] != null
                ? _parseDateTime(json['end_date'] ?? json['endDate'])
                : null,
        createdAt: _parseDateTime(
          json['createdAt'] ?? json['created_at'] ?? DateTime.now().toString(),
        ),
        updatedAt: _parseDateTime(
          json['updatedAt'] ?? json['updated_at'] ?? DateTime.now().toString(),
        ),
        description: json['description'],
        lastUpdated: _parseDateTime(
          json['last_updated'] ??
              json['updatedAt'] ??
              DateTime.now().toString(),
        ),
        isSynced:
            json['isSynced'] ?? true, // Assume synced if coming from server
        version: json['version'] ?? 0,
      );
    } catch (e) {
      throw FormatException('Failed to parse Event: $e\nJSON: $json');
    }
  }

  static DateTime _parseDateTime(dynamic date) {
    if (date is DateTime) return date;
    if (date == null) return DateTime.now();

    try {
      // Try parsing ISO format first
      if (date is String) {
        return DateTime.parse(date);
      }

      // Handle other cases if needed
      return DateTime.now();
    } catch (e) {
      print('Failed to parse date: $date');
      return DateTime.now();
    }
  }

  Event copyWith({
    String? id,
    String? title,
    DateTime? startDate,
    DateTime? endDate,
    String? description,
    bool? isSynced,
    DateTime? lastUpdated,
    int? version,
    bool? isDeleted,
    String? userId,
    String? changeType,
  }) {
    return Event(
      isDeleted: isDeleted ?? this.isDeleted,
      createdAt: createdAt,
      updatedAt: updatedAt,
      userId: userId ?? this.userId,
      id: id ?? this.id,
      title: title ?? this.title,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      description: description ?? this.description,
      isSynced: isSynced ?? this.isSynced,
      lastUpdated: lastUpdated ?? this.lastUpdated,
      version: version ?? this.version,
      changeType: changeType ?? this.changeType,
    );
  }

  // Static copy method
  static Event copy(Event other) {
    return Event(
      // eventId: other.eventId,
      isDeleted: other.isDeleted,
      createdAt: other.createdAt,
      updatedAt: other.updatedAt,
      id: other.id,
      userId: other.userId,
      title: other.title,
      startDate: other.startDate,
      description: other.description,
      isSynced: other.isSynced,
      lastUpdated: other.lastUpdated,
      version: other.version,
    );
  }

  factory Event.create({
    required String id,
    required String title,
    String? description,
    required DateTime startDate,
    DateTime? endDate,
    required userId,
    bool isDeleted = false,
    String? changeType,
  }) {
    final now = DateTime.now();
    return Event(
      isDeleted: isDeleted,
      id: id,
      title: title,
      userId: userId, // In a real app, use actual user ID
      startDate: startDate,
      endDate: endDate,
      createdAt: now,
      lastUpdated: now,
      updatedAt: now,
      description: description,
      isSynced: false, // New events are unsynced by default
      version: 0,
      changeType: changeType,
    );
  }
}
