# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import crop_analysis_pb2 as crop__analysis__pb2


class CropAnalysisServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeCrop = channel.unary_unary(
                '/crop_analysis.CropAnalysisService/AnalyzeCrop',
                request_serializer=crop__analysis__pb2.CropAnalysisRequest.SerializeToString,
                response_deserializer=crop__analysis__pb2.CropAnalysisResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/crop_analysis.CropAnalysisService/HealthCheck',
                request_serializer=crop__analysis__pb2.HealthRequest.SerializeToString,
                response_deserializer=crop__analysis__pb2.HealthResponse.FromString,
                )


class CropAnalysisServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeCrop(self, request, context):
        """Main method for crop analysis with image and context
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CropAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeCrop': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCrop,
                    request_deserializer=crop__analysis__pb2.CropAnalysisRequest.FromString,
                    response_serializer=crop__analysis__pb2.CropAnalysisResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=crop__analysis__pb2.HealthRequest.FromString,
                    response_serializer=crop__analysis__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crop_analysis.CropAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CropAnalysisService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeCrop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crop_analysis.CropAnalysisService/AnalyzeCrop',
            crop__analysis__pb2.CropAnalysisRequest.SerializeToString,
            crop__analysis__pb2.CropAnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/crop_analysis.CropAnalysisService/HealthCheck',
            crop__analysis__pb2.HealthRequest.SerializeToString,
            crop__analysis__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
