# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crop_analysis.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63rop_analysis.proto\x12\rcrop_analysis\"\xc5\x01\n\x13\x43ropAnalysisRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x12\n\nimage_name\x18\x02 \x01(\t\x12\x12\n\nimage_type\x18\x03 \x01(\t\x12\x11\n\tcrop_type\x18\x04 \x01(\t\x12\x18\n\x10observed_problem\x18\x05 \x01(\t\x12\x16\n\x0eplant_age_days\x18\x06 \x01(\x05\x12\x1c\n\x14recent_weather_event\x18\x07 \x01(\x08\x12\x0f\n\x07user_id\x18\x08 \x01(\t\"\x9f\x02\n\x14\x43ropAnalysisResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tdiagnosis\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x0f\n\x07\x64isease\x18\x04 \x01(\t\x12\x10\n\x08severity\x18\x05 \x01(\t\x12\x13\n\x0bsuggestions\x18\x06 \x03(\t\x12+\n\ttreatment\x18\x07 \x03(\x0b\x32\x18.crop_analysis.Treatment\x12\x12\n\nprevention\x18\x08 \x03(\t\x12\x12\n\nreferences\x18\t \x03(\t\x12\x17\n\x0fprocessing_time\x18\n \x01(\x01\x12\x12\n\nmodel_used\x18\x0b \x01(\t\x12\x15\n\rerror_message\x18\x0c \x01(\t\"C\n\tTreatment\x12\x0f\n\x07product\x18\x01 \x01(\t\x12\x13\n\x0b\x61pplication\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"B\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t2\xb9\x01\n\x13\x43ropAnalysisService\x12V\n\x0b\x41nalyzeCrop\x12\".crop_analysis.CropAnalysisRequest\x1a#.crop_analysis.CropAnalysisResponse\x12J\n\x0bHealthCheck\x12\x1c.crop_analysis.HealthRequest\x1a\x1d.crop_analysis.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crop_analysis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CROPANALYSISREQUEST']._serialized_start=39
  _globals['_CROPANALYSISREQUEST']._serialized_end=236
  _globals['_CROPANALYSISRESPONSE']._serialized_start=239
  _globals['_CROPANALYSISRESPONSE']._serialized_end=526
  _globals['_TREATMENT']._serialized_start=528
  _globals['_TREATMENT']._serialized_end=595
  _globals['_HEALTHREQUEST']._serialized_start=597
  _globals['_HEALTHREQUEST']._serialized_end=612
  _globals['_HEALTHRESPONSE']._serialized_start=614
  _globals['_HEALTHRESPONSE']._serialized_end=680
  _globals['_CROPANALYSISSERVICE']._serialized_start=683
  _globals['_CROPANALYSISSERVICE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
